### ISSUE TITLE
Simplify user timezone feature

### ISSUE THREAD

**Issue by jnhallquist** [jnhallquist/discord-reminders-bot#31]
Currently a user who has not set a timezone needs to figure out on their own what their timezone is.
This wouldn't be the worst thing if the format wasn't specific:
`PST vs America/Los_Angeles` for example

It would be more user friendly to provide an indexed list for them to choose from with the standard timezones and allow them to input their own timezone if it is something less ordinary.
This could look something like:
```
rbot timezone list
1. America/Los_Angeles
.
.
.
N. Asia/Tokyo

rbot timezone set 1
or
rbot timezone set America/Los_Angeles
```

**Comment by jnhallquist** [comment]
@JustinHallquist 

I'm thinking that the indexed list can contain the following (not verbatim, but will display the `America/City` values):

```
{"value":"America/Puerto_Rico","name":"Puerto Rico (Atlantic)"},
{"value":"America/New_York","name":"New York (Eastern)"},
{"value":"America/Chicago","name":"Chicago (Central)"},
{"value":"America/Denver","name":"Denver (Mountain)"},
{"value":"America/Phoenix","name":"Phoenix (MST)"},
{"value":"America/Los_Angeles","name":"Los Angeles (Pacific)"},
{"value":"America/Anchorage","name":"Anchorage (Alaska)"},
{"value":"Pacific/Honolulu","name":"Honolulu (Hawaii)"}
```

I  am under the assumption that most users will be located in the United States, so I don't intend to add non-U.S. timezones to this list. After all, users will still be able to add a custom tz.

**Comment by JustinHallquist** [comment]
I would consider adding one european and one asian time zone as well so they can see the format, otherwise that looks solid
